// Mocks generated by Mockito 5.4.6 from annotations
// in casa_limpa/test/integracao_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

import 'integracao_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [Validador].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidador extends _i1.Mock implements _i2.Validador {
  MockValidador() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String? validarConfirmarSenha(String? v, String? s) =>
      (super.noSuchMethod(Invocation.method(#validarConfirmarSenha, [v, s]))
          as String?);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> login(String? email, String? senha) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, senha]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String> registrar(String? email, String? senha) =>
      (super.noSuchMethod(
            Invocation.method(#registrar, [email, senha]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#registrar, [email, senha]),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>?> obterUsuario(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#obterUsuario, [uid]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> salvarUsuario(String? uid, Map<String, dynamic>? dados) =>
      (super.noSuchMethod(
            Invocation.method(#salvarUsuario, [uid, dados]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> atualizarStatusFaxina(
    String? faxinaId,
    String? novoStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarStatusFaxina, [faxinaId, novoStatus]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
