// Mocks generated by Mockito 5.4.6 from annotations
// in casa_limpa/test/logica_lista_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

import 'logica_lista_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PropostaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPropostaRepository extends _i1.Mock
    implements _i2.PropostaRepository {
  MockPropostaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.PropostaDoc>> listarPropostas() =>
      (super.noSuchMethod(
            Invocation.method(#listarPropostas, []),
            returnValue: _i3.Future<List<_i2.PropostaDoc>>.value(
              <_i2.PropostaDoc>[],
            ),
          )
          as _i3.Future<List<_i2.PropostaDoc>>);
}

/// A class which mocks [PropostaDoc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPropostaDoc extends _i1.Mock implements _i2.PropostaDoc {
  MockPropostaDoc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  Map<String, dynamic> data() =>
      (super.noSuchMethod(
            Invocation.method(#data, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
