name: casa_limpa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^4.8.0
  firebase_auth: ^6.5.0
  cloud_firestore: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.30.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true